# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-08 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
